name: backend
description: A sample command-line application.
version: 1.0.10+12
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

dependencies:
# Mime
  mime: ^1.0.5

# Path
  path: ^1.9.0

# Shelf
  shelf: ^1.4.1

# Shelf_cors_headers
  shelf_cors_headers: ^0.1.5

# Shelf_multipart
  shelf_multipart: ^2.0.0

# shelf_router
  shelf_router: ^1.1.4

# Sqlite3
  sqlite3: ^2.4.6
 

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
